"""
Generated by generator/generator.py - 2023-05-10 20:22:42.735267
"""
import pytest


@pytest.fixture()
def calendar_fixture_response():
    return {'releaseDate': 'string', 'mediaItem': {'id': 0, 'title': 'string', 'releaseDate': 'string', 'slug': 'string', 'mediaType': 'audiobook', 'seen': True}, 'episode': {'id': 0, 'title': 'string', 'episodeNumber': 0, 'seasonNumber': 0, 'releaseDate': 'string', 'isSpecialEpisode': True, 'seen': True}}
