"""
Generated by generator/generator.py - 2023-05-09 14:40:06.285643
"""
import pytest


@pytest.fixture()
def config_fixture_response():
    return {'enableRegistration': True, 'tmdbLang': 'en', 'audibleLang': 'us', 'serverLang': 'en', 'igdbClientId': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'igdbClientSecret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'noUsers': False, 'demo': False}
