"""
Generated by generator/generator.py - 2023-05-09 14:40:06.285643
"""
from pymediatracker.objects.config import MediaTrackerConfig
from tests.responses.config_fixture import config_fixture_response

def test_config(config_fixture_response):
    obj = MediaTrackerConfig(config_fixture_response)
    assert obj.enableRegistration == config_fixture_response['enableRegistration']
    assert obj.tmdbLang == config_fixture_response['tmdbLang']
    assert obj.audibleLang == config_fixture_response['audibleLang']
    assert obj.serverLang == config_fixture_response['serverLang']
    assert obj.igdbClientId == config_fixture_response['igdbClientId']
    assert obj.igdbClientSecret == config_fixture_response['igdbClientSecret']
    assert obj.noUsers == config_fixture_response['noUsers']
    assert obj.demo == config_fixture_response['demo']
