"""
Generated by generator/generator.py - 2023-05-10 20:22:42.735267
"""
from pymediatracker.objects.calendar import MediaTrackerCalendar
from tests.responses.calendar_fixture import calendar_fixture_response

def test_calendar(calendar_fixture_response):
    obj = MediaTrackerCalendar(calendar_fixture_response)
    assert obj.releaseDate == calendar_fixture_response['releaseDate']
    assert obj.mediaItem.id == calendar_fixture_response['mediaItem']['id']
    assert obj.mediaItem.title == calendar_fixture_response['mediaItem']['title']
    assert obj.mediaItem.releaseDate == calendar_fixture_response['mediaItem']['releaseDate']
    assert obj.mediaItem.slug == calendar_fixture_response['mediaItem']['slug']
    assert obj.mediaItem.mediaType == calendar_fixture_response['mediaItem']['mediaType']
    assert obj.mediaItem.seen == calendar_fixture_response['mediaItem']['seen']
    assert obj.episode.id == calendar_fixture_response['episode']['id']
    assert obj.episode.title == calendar_fixture_response['episode']['title']
    assert obj.episode.episodeNumber == calendar_fixture_response['episode']['episodeNumber']
    assert obj.episode.seasonNumber == calendar_fixture_response['episode']['seasonNumber']
    assert obj.episode.releaseDate == calendar_fixture_response['episode']['releaseDate']
    assert obj.episode.isSpecialEpisode == calendar_fixture_response['episode']['isSpecialEpisode']
    assert obj.episode.seen == calendar_fixture_response['episode']['seen']
